# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  win: circleci/windows@2.2.0
  aws-cli: circleci/aws-cli@2.1.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
      docker:
        - image: "cimg/base:stable"
      steps:
        - node/install
        - checkout
        - aws-cli/setup
        - run:
            name: Front-End install
            command: |
              npm run frontend:install
        - run:
            name: Back-End install
            command: |
              npm run backend:install
        - run:
            name: Front-End build
            command: |
              npm run frontend:build
        - run:
            name: Back-End build
            command: |
              npm run backend:build
        - run:
            name: Front-End deploy
            command: |
              npm run frontend:deploy

