# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  win: circleci/windows@2.2.0
  aws-cli: circleci/aws-cli@2.1.0
  browser-tools: circleci/browser-tools@1.2.3

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
      docker:
        - image: cimg/node:16.13.1-browsers #circleci/node:6-browsers #"cimg/base:stable"
          environment:
            CHROME_BIN: "/usr/bin/google-chrome"
      steps:
        - checkout
        - aws-cli/setup
        - node/install:
            install-yarn: false
            node-version: '16.13'
        - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
        - run:
            name: Front-End install
            command: |
              npm run frontend:install
        - run:
            name: Back-End install
            command: |
              npm run backend:install
        - run:
            name: front-End test
            command: |
              npm run frontend:test
        - run:
            name: Back-End test
            command: |
              npm run backend:test
        - run:
            name: Front-End build
            command: |
              npm run frontend:build
        - run:
            name: Back-End build
            command: |
              npm run backend:build
        - run:
            name: Front-End deploy
            command: |
              npm run frontend:deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

